Algoritmo "semnome"


Var
nome_1,nome_2:caractere
idade_1,idade_2:inteiro
idade_media:real



Inicio
escreva("qual o nome 1:")
leia(nome_1)
escreva("qual a idade 1:")
leia(idade_1)
escreva("qual o nome 2:")
leia(nome_1)
escreva("qual a idade 2:")
leia(idade_2)
idade_media<- (idade_1+idade_2)/2
escreval("a idade media o nome 1 ",nome_1," e o nome 2 é ",idade_media)




Fimalgoritmo